mappings:
  SharethisTest: SunnysideUp\ShareThis\SharethisTest
  FacebookFeed_UpdateTask: SunnysideUp\ShareThis\FacebookFeed_UpdateTask
  ShareThisSiteConfigDE: SunnysideUp\ShareThis\ShareThisSiteConfigDE
  SocialNetworksSTE: SunnysideUp\ShareThis\SocialNetworksSTE
  ShareThisSTE: SunnysideUp\ShareThis\ShareThisSTE
  SocialNetworkingModelAdmin: SunnysideUp\ShareThis\SocialNetworkingModelAdmin
  FacebookFeed_Page: SunnysideUp\ShareThis\FacebookFeed_Page
  ShareThisDataObject: SunnysideUp\ShareThis\ShareThisDataObject
  MyTwitterData: SunnysideUp\ShareThis\MyTwitterData
  FacebookFeed_Item: SunnysideUp\ShareThis\FacebookFeed_Item
  SocialNetworkingLinksDataObject: SunnysideUp\ShareThis\SocialNetworkingLinksDataObject
  MyTwitter: SunnysideUp\ShareThis\MyTwitter
  simple_html_dom_node: SunnysideUp\ShareThis\thirdparty\simple_html_dom_node
  simple_html_dom: SunnysideUp\ShareThis\thirdparty\simple_html_dom
  SilverstripeFacebookConnector: SunnysideUp\ShareThis\SilverstripeFacebookConnector
  ShareThisOptions: SunnysideUp\ShareThis\ShareThisOptions
  RemoveFacebookItemController: SunnysideUp\ShareThis\RemoveFacebookItemController
  Services_JSON: SunnysideUp\ShareThis\Services_JSON
  Services_JSON_Error: SunnysideUp\ShareThis\Services_JSON_Error
  TwitterOAuth: SunnysideUp\ShareThis\TwitterOAuth
  OAuthException: SunnysideUp\ShareThis\OAuthException
  OAuthConsumer: SunnysideUp\ShareThis\OAuthConsumer
  OAuthToken: SunnysideUp\ShareThis\OAuthToken
  OAuthSignatureMethod: SunnysideUp\ShareThis\OAuthSignatureMethod
  OAuthSignatureMethod_HMAC_SHA1: SunnysideUp\ShareThis\OAuthSignatureMethod_HMAC_SHA1
  OAuthSignatureMethod_PLAINTEXT: SunnysideUp\ShareThis\OAuthSignatureMethod_PLAINTEXT
  OAuthSignatureMethod_RSA_SHA1: SunnysideUp\ShareThis\OAuthSignatureMethod_RSA_SHA1
  OAuthRequest: SunnysideUp\ShareThis\OAuthRequest
  OAuthServer: SunnysideUp\ShareThis\OAuthServer
  OAuthDataStore: SunnysideUp\ShareThis\OAuthDataStore
  OAuthUtil: SunnysideUp\ShareThis\OAuthUtil
