---
Name: sharethis
Before: 'mysite/*'
After: 'framework/*'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SunnysideUp\ShareThis\ShareThisSiteConfigDE

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SunnysideUp\ShareThis\ShareThisSTE
    - SunnysideUp\ShareThis\SocialNetworksSTE

SilverStripe\Core\Manifest\ModuleManifest:
  project: silverstripe-sharethis
---
Only:
  classexists: DataObjectSorterDOD
---
SunnysideUp\ShareThis\ShareThisDataObject:
  extensions:
    - DataObjectSorterDOD

SunnysideUp\ShareThis\SocialNetworkingLinksDataObject:
  extensions:
    - DataObjectSorterDOD
